### ISSUE TITLE
Add class icons to Job Dropdown and read-only name

### ISSUE THREAD

**Issue by jedmund** [jedmund/hensei-web#153]
### Tasks
- [ ] Add slug to Job table for referencing images later
- [ ] Download images one by one :)
- [ ] Update display in dropdown
- [ ] Update display in dropdown trigger
- [ ] Update display on read-only header
